# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=20000)),
                ('slug', models.CharField(max_length=20)),
                ('category_id', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_category_name', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
    ]
